server:
  port: 8010

spring:
  application:
    name: zuul-gateway
  http:
    multipart:
      maxFileSize: 1000Mb
      maxRequestSize: 1000Mb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
management:
  security:
    enabled: false
zuul:
  sensitive-headers:
  host:
    socket-timeout-millis: 999999999
    connect-timeout-millis: 99999999
ribbon:
  ReadTimeout: 99999999
  ConnectTimeout: 99999999